### ISSUE TITLE
Backup system not working

### ISSUE THREAD

**Issue by Ashenboy** [Siris2314/NecroAtomicBot#307]
```
[antiCrash] :: Unhandled Rejection/CatchDiscordAPIError: Invalid Form Body
name: Could not interpret "{'name': 'sd', 'type': 2, 'parent': None}" as string.
DiscordAPIError: Invalid Form Body
name: Could not interpret "{'name': 'sd', 'type': 2, 'parent': None}" as string.
    at RequestHandler.execute (C:\Users\ashen\OneDrive\Documents\Discord\general-bot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)     
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\ashen\OneDrive\Documents\Discord\general-bot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)   
    at async GuildChannelManager.create (C:\Users\ashen\OneDrive\Documents\Discord\general-bot\node_modules\discord.js\src\managers\GuildChannelManager.js:176:18) {
  method: 'post',
  path: '/guilds/1113685711544123402/channels',
  code: 50035,
  httpStatus: 400,
  requestData: {
    json: {
      name: [Object],
      topic: undefined,
      type: 0,
      nsfw: undefined,
      bitrate: undefined,
      user_limit: undefined,
      parent_id: undefined,
      position: undefined,
      permission_overwrites: undefined,
      rate_limit_per_user: undefined,
      rtc_region: undefined,
      video_quality_mode: undefined,
      available_tags: undefined,
      default_reaction_emoji: undefined,
      default_sort_order: undefined,
      default_forum_layout: undefined
    },
    files: []
  }
} Promise {
  <rejected> DiscordAPIError: Invalid Form Body
  name: Could not interpret "{'name': 'sd', 'type': 2, 'parent': None}" as string.
      at RequestHandler.execute (C:\Users\ashen\OneDrive\Documents\Discord\general-bot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)   
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async RequestHandler.push (C:\Users\ashen\OneDrive\Documents\Discord\general-bot\node_modules\discord.js\src\rest\RequestHandler.js:51:14) 
```

**Comment by Siris2314** [comment]
Fixed check the new system out here:

https://github.com/Siris2314/NecroAtomicBot/blob/main/commands/administration/backup.js
